### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by mathieuruellan** [infinitesunrise/carsinbikelanes#21]
During the "dockerification":
because of mysqli::begin_transaction(), php 5.5+ (instead of 5.2+) is mandatory
and also php5-gd

Hope that helps other guys!

**Comment by infinitesunrise** [comment]
Whoops, updated the PHP requirement in the README: 610c8b2f4491350aca28405f8553bd723a18abad

As for the other Docker-centric issues I'm going to wait for a pull request from you, @mattkime or @DigitallyBorn since you all seem to be working word Docker compatibility.
