### ISSUE TITLE
Unable to update GPS coordinates

### ISSUE THREAD

**Issue by mathieuruellan** [infinitesunrise/carsinbikelanes#23]
When i click on coordinates, i've got a blank rectangle with alpha under the coordinates.
![capture d ecran_2016-09-24_18-14-25](https://cloud.githubusercontent.com/assets/1267936/18809683/c182aa60-8282-11e6-9cd5-ed36a689928e.png)

**Comment by infinitesunrise** [comment]
Which browser is this? That box should be loading a map with which to select change the GPS point. Beyond a browser issue it's also possible that map settings are not set up correctly in the settings tab.

**Comment by mathieuruellan** [comment]
I'm using chromium on debian testing. I will try with other browsers!
For the map configuration, it works on the main and submit page.

**Comment by mathieuruellan** [comment]
I've got the same issue on firefox. and google chrome (version 55.0.2859.0-1)

**Comment by mathieuruellan** [comment]
Here is my config file

<?php

//----------------------------------------------//
// CONFIGURATION
//----------------------------------------------//

$config = array(
'sqlhost' => 'mysql',
'sqluser' => 'cibl',
'sqlpass' => 'cibl',
'database' => '########',
'use_providers_plugin' => 1,
'leaflet_provider' => 'OpenStreetMap',
'map_url' => 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
'use_google' => 0,
'google_api_key' => '',
'google_extra_layer' => 'NONE',
'use_bing' => 0,
'bing_api_key' => '',
'bing_imagery' => 'Road',
'max_view' => 50,
'north_bounds' => 47.29,
'south_bounds' => 47.141,
'east_bounds' => -1.43,
'west_bounds' => -1.68,
'center_lat' => 47.2155,
'center_long' => -1.555,
'mobile_center_lat' => 47.2155,
'mobile_center_long' => -1.555,
'site_name' => 'CARSINBIKELANES',
'comments' => '',
'disqus' => '',
'openalpr_api_key' => '',
'about_text' => '&lt;h3&gt;About CARSINBIKELANES&lt;/h3&gt;
&lt;p&gt;CIBL is a browsable geographic database for crowd-sourcing traffic violation reports. Originally designed to publicly track illegal automotive encroachment into New York City bike l
anes at carsinbikelanes.nyc, CIBL can be adapted for to document any sort of observable traffic violations within a defined geographic area. CIBL records the time, date, cross streets, GPS c
oordinates, user description and image of each record submitted. CIBL\'s setup wizard should be able to self-deploy in a LAMP environment upon navigating to /index.php in a web browser.&lt;/
p&gt;'
);

$connection = mysqli_connect($config['sqlhost'],$config['sqluser'],$config['sqlpass'],$config['database']);

?>

**Comment by infinitesunrise** [comment]
fixed by 73982257441130af7714e3a00d41ef612fd97f7d
