### ISSUE TITLE
be notified when a new item is the queue.

### ISSUE THREAD

**Issue by mathieuruellan** [infinitesunrise/carsinbikelanes#24]
I didn't find where to configure smtp to be notified when a new item is in the queue.

**Comment by infinitesunrise** [comment]
No SMTP settings yet, all email sent through php's mail() function for the time being which I believe relies on the http server having correct mail settings? Would very much like to have SMTP options in the future. Closing this issue and opening a new one for that.

**Comment by mathieuruellan** [comment]
Ok, I'm not confident with php.
But with docker, it will be a php.ini template, a sed and that's it ;)!
