### ISSUE TITLE
Can't load external http link with https host

### ISSUE THREAD

**Issue by mathieuruellan** [infinitesunrise/carsinbikelanes#27]
I'm hosting with https, and  modern browsers don't accept to load url that are not https://.
Use a protocol relative url? http://stackoverflow.com/questions/9161769/url-without-httphttps

![capture d ecran_2016-09-24_20-11-23](https://cloud.githubusercontent.com/assets/1267936/18810311/5964f4e0-8293-11e6-8a5c-f5457759d5dd.png)

**Comment by infinitesunrise** [comment]
fixed by 73982257441130af7714e3a00d41ef612fd97f7d, thanks!
