### ISSUE TITLE
change cdn of leaflet.js

### ISSUE THREAD

**Issue by mathieuruellan** [infinitesunrise/carsinbikelanes#28]
Because of a wrong ssl certificate cdn.leafletjs.com is not usable ( https://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css ).

But cloudflare works fine https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js

https://github.com/Leaflet/Leaflet/issues/1824

**Comment by infinitesunrise** [comment]
fixed by 73982257441130af7714e3a00d41ef612fd97f7d
