### ISSUE TITLE
do not zoom map to coordinates when image reports 0,0 lat long

### ISSUE THREAD

**Issue by mattkime** [infinitesunrise/carsinbikelanes#41]
I've attached a file that had this EXIF data so you can see the associated problems.

![file1279](https://cloud.githubusercontent.com/assets/216176/19246799/266dcf16-8ef6-11e6-80b3-a4cf8979deee.JPG)

**Comment by infinitesunrise** [comment]
Thanks, didn't even realize I hadn't included a check for this. It'll be in my next commit.

**Comment by infinitesunrise** [comment]
fixed in 9dbc52b8504d92f4579536f0ebefdb66c398e316
