### ISSUE TITLE
EXIF time extraction is wrong

### ISSUE THREAD

**Issue by mattkime** [infinitesunrise/carsinbikelanes#48]
Attached an image captured at 5:30pm. the site is reporting that it was taken at 1:30pm

![virb0002](https://cloud.githubusercontent.com/assets/216176/19877407/4c09fd88-9fb5-11e6-8558-eea78419b70b.JPG)

**Comment by rschmunk** [comment]
Photoshop "file info" reports that the image has a timestamp of 17:30, with no timezone information.

Is the site expecting that the timestamp is UTC and subtracting 4 hours to get EDT?

**Comment by infinitesunrise** [comment]
Ugh I see, this is due to a discrepancy in the way that Chrome and Firefox interpret the js constructor for Date(). One browser offsets to local timezone and one interprets as UTC. I tested on FF assuming Chrome would be the same, of course they're not. I can get a fix in later tonight.

**Comment by infinitesunrise** [comment]
The fix is in! 9aff59880199756777aa4878fd49f1189f83f8a8 I basically abandoned the JS Date() class and now rely instead on string parsing.

Added both here and on carsinbikelanes,nyc, give it a whirl please.
