### ISSUE TITLE
upload details confirm shows date of ocurrence as nan/nan/nan nan:nanpm

### ISSUE THREAD

**Issue by mattkime** [infinitesunrise/carsinbikelanes#49]
![screen shot 2016-11-01 at 12 51 32 pm](https://cloud.githubusercontent.com/assets/216176/19898364/234f56ae-a032-11e6-9892-94adb9a4663b.png)

**Comment by infinitesunrise** [comment]
Yeah it's just making fun of you: "Nyah nyah nyah nyah!"

Kidding. Thank you for this, seems my date functions haven't been completely hammered-out yet. Shouldn't be hard to fix. Then again, that's what I thought of the first dozen date fixes...

**Comment by infinitesunrise** [comment]
Should be fixed by 9aff59880199756777aa4878fd49f1189f83f8a8
